/* Generated By:JavaCC: Do not edit this line. CFParserConstants.java */
/*
 * $Id$ 
 */

package parser;

public interface CFParserConstants {

  int EOF = 0;
  int INCLUDE = 8;
  int CNF = 9;
  int AXIOM = 10;
  int CARC = 11;
  int OBSERVATIONS = 12;
  int BACKGROUND = 13;
  int HYPOTHESIS = 14;
  int INDUCTION_FIELD = 15;
  int SIZE = 16;
  int LENGTH = 17;
  int TYPE = 18;
  int ALL = 19;
  int POS_ALL = 20;
  int NEG_ALL = 21;
  int HEADMODE = 22;
  int SKOLEM = 23;
  int BODYMODE = 24;
  int POSITIVE = 25;
  int NEGATIVE = 26;
  int CONSTANT = 27;
  int INTEGER = 28;
  int POS_ACTUAL_NUM = 29;
  int NEG_ACTUAL_NUM = 30;
  int VARIABLE = 31;
  int UNNAMED = 32;
  int LOWERCASE = 33;
  int LETTER = 34;
  int DIGIT = 35;
  int UPPERCASE = 36;
  int POS = 37;
  int NEG = 38;
  int POS_NEG = 39;
  int GROUND = 40;
  int PERIOD = 41;
  int FILENAME = 42;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"include\"",
    "\"cnf\"",
    "\"axiom\"",
    "\"carc\"",
    "\"obs\"",
    "\"bg\"",
    "\"hypo\"",
    "\"induction_field\"",
    "\"size\"",
    "\"length\"",
    "\"type\"",
    "\"all\"",
    "\"pos_all\"",
    "\"neg_all\"",
    "\"modeh\"",
    "\"skolem\"",
    "\"modeb\"",
    "\"pos\"",
    "\"neg\"",
    "<CONSTANT>",
    "<INTEGER>",
    "<POS_ACTUAL_NUM>",
    "<NEG_ACTUAL_NUM>",
    "<VARIABLE>",
    "\"_\"",
    "<LOWERCASE>",
    "<LETTER>",
    "<DIGIT>",
    "<UPPERCASE>",
    "<POS>",
    "<NEG>",
    "<POS_NEG>",
    "\"#\"",
    "\".\"",
    "<FILENAME>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
    "\":\"",
  };

}
